name: Deploy to GKE

on:
  push:
    branches:
      - master  # Adjust this branch name as per your requirement

jobs:
  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'DEVELOPMENT'
    steps:
      # Checkout the repository
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'
     
      # Configure kubectl
      - name: Connect to the GKE cluster
        run: gcloud container clusters get-credentials dev-task-cluster-dev --zone us-central1-c --project ${{ secrets.PROJECT_ID }}
        
      - name: Install kubectl and setup GKE AUTH PLUGIN
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin kubectl -y
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
      - name: Check Kubectl command
        run: |
          kubectl get svc
      - name: Install helm chart
        run: |
          helm upgrade --install  wordpress-app wordpress --set secret.wpPassword="${{ secrets.DB_PASSWORD }}",secret.wpUsername="${{ secrets.DB_USERNAME }}"
  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'PRODUCTION'
    needs: deploy-dev
    steps:
        # Checkout the repository
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCLOUD_AUTH }}'
     
      # Configure kubectl
      - name: Connect to the GKE cluster
        run: gcloud container clusters get-credentials prod-task-cluster-prod --zone us-east1-b --project ${{ secrets.PROJECT_ID }}
        
      - name: Install kubectl and setup GKE AUTH PLUGIN
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin kubectl -y
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
      - name: Check Kubectl command
        run: |
          kubectl get svc
      - name: Install helm chart
        run: |
          helm upgrade --install  wordpress-app wordpress --set secret.wpPassword="${{ secrets.DB_PASSWORD }}",secret.wpUsername="${{ secrets.DB_USERNAME }}"



